// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Yui-wy/asset-management/app/form/service/internal/biz"
	"github.com/Yui-wy/asset-management/app/form/service/internal/conf"
	"github.com/Yui-wy/asset-management/app/form/service/internal/data"
	"github.com/Yui-wy/asset-management/app/form/service/internal/server"
	"github.com/Yui-wy/asset-management/app/form/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, machine *conf.Machine, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, machine, logger)
	if err != nil {
		return nil, nil, err
	}
	scrappedRepo := data.NewScrappedRepo(dataData, logger)
	scrappedUseCase := biz.NewScrappedUseCase(scrappedRepo, logger)
	storageRepo := data.NewStorageRepo(dataData, logger)
	storageUseCase := biz.NewStorageUseCase(storageRepo, logger)
	formService := service.NewFormService(logger, scrappedUseCase, storageUseCase)
	grpcServer := server.NewGRPCServer(confServer, formService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
