package setting

var ASSETS_STATE_MAP = map[int32]string{
	ASSETS_STATE_UNKNOWN:     "未知状态, 请确认",
	ASSETS_STATE_ST:          "库内",
	ASSETS_STATE_ST_APPLY:    "入库申请中",
	ASSETS_STATE_ORDER:       "采购中",
	ASSETS_STATE_ORDER_APPLY: "采购申请中",
	ASSETS_STATE_SP:          "报废",
	ASSETS_STATE_SP_APPLY:    "报废申请中",
	ASSETS_STATE_CHECKING:    "检修中",
	ASSETS_STATE_REPAIRING:   "修理中",
	ASSETS_STATE_ST_FAIL:     "入库失败",
}

const (
	ASSETS_STATE_UNKNOWN     = -1
	ASSETS_STATE_ST          = 1
	ASSETS_STATE_ST_APPLY    = 2
	ASSETS_STATE_ORDER       = 3
	ASSETS_STATE_ORDER_APPLY = 4
	ASSETS_STATE_SP          = 5
	ASSETS_STATE_SP_APPLY    = 6
	ASSETS_STATE_CHECKING    = 7
	ASSETS_STATE_REPAIRING   = 8
	ASSETS_STATE_ST_FAIL     = 9
)

const (
	SUPER_ADMIN_USER = 0
	AREA_ADMIN_USER  = 1
	AREA_USER        = 2
)
