// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Yui-wy/asset-management/app/assets/service/internal/biz"
	"github.com/Yui-wy/asset-management/app/assets/service/internal/conf"
	"github.com/Yui-wy/asset-management/app/assets/service/internal/data"
	"github.com/Yui-wy/asset-management/app/assets/service/internal/server"
	"github.com/Yui-wy/asset-management/app/assets/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	areaRepo := data.NewAreaRepo(dataData, logger)
	areaUseCase := biz.NewAreaUseCase(areaRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	classRepo := data.NewClassRepo(dataData, logger)
	classUseCase := biz.NewClassUseCase(classRepo, logger)
	assetRepo := data.NewAssetRepo(dataData, logger)
	assetUseCase := biz.NewAssetUseCase(assetRepo, logger)
	assetsService := service.NewAssetsService(logger, areaUseCase, userUseCase, classUseCase, assetUseCase)
	grpcServer := server.NewGRPCServer(confServer, assetsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
